# Build stage
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app
COPY --from=build /app/target/springapp-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8082

USER 1000:1000

CMD ["java", "-jar", "app.jar"]